### ISSUE TITLE
how to use it to train ?

### ISSUE THREAD

**Issue by Andrew05200** [ismail-mebsout/Parsing-PDFs-using-YOLOV3#5]
I cannot find the train func, where is it ? can you share ?
I want train the model  on custom datasets.

**Comment by ismail-mebsout** [comment]
Hello Andrew,

In order to train the model on custom datasets, I suggest to use the following yolov3 repository:
https://github.com/ultralytics/yolov3

Best regards,
Ismail Mebsout
